'use strict';

const canvas = document.querySelector('#screen'); const ctx = canvas.getContext('2d', { alpha: false }); const image = ctx.createImageData(240, 160); const imageWords = new Uint32Array(image.data.buffer); let worker = null; let running = true;

function paint(frame) { imageWords.set(frame); ctx.putImageData(image, 0, 0); }
function keyName(event) { return ({ z: 'a', x: 'b', Enter: 'start', Shift: 'select', ArrowUp: 'up', ArrowDown: 'down', ArrowLeft: 'left', ArrowRight: 'right', a: 'l', s: 'r' })[event.key]; }
function button(key, down) { worker?.postMessage({ type: 'button', key, down }); }
window.addEventListener('keydown', (event) => { const key = keyName(event); if (key) { event.preventDefault(); button(key, true); } }); window.addEventListener('keyup', (event) => { const key = keyName(event); if (key) { event.preventDefault(); button(key, false); } });
document.querySelectorAll('[data-key]').forEach((control) => { const key = control.dataset.key; control.addEventListener('pointerdown', () => button(key, true)); control.addEventListener('pointerup', () => button(key, false)); control.addEventListener('pointercancel', () => button(key, false)); control.addEventListener('pointerleave', () => button(key, false)); });
document.querySelector('#pause').addEventListener('click', (event) => { running = !running; worker?.postMessage({ type: 'pause', paused: !running }); event.currentTarget.textContent = running ? 'Pausar' : 'Continuar'; }); document.querySelector('#reset').addEventListener('click', () => worker?.postMessage({ type: 'reset' }));

async function init() { const payload = await window.duopocket.getRom(); if (!payload) { document.querySelector('#status').textContent = 'ROM indisponível'; return; } worker = new Worker('./gba-worker-bundle.js'); worker.onmessage = (event) => { const message = event.data || {}; if (message.type === 'frame') paint(new Uint32Array(message.pixels)); else if (message.type === 'ready') document.querySelector('#status').textContent = 'ARM7TDMI · 59,7 FPS · Flash 1M'; else if (message.type === 'save') window.duopocket.saveRom(new Uint8Array(message.bytes)); }; worker.onerror = (error) => { console.error(error); document.querySelector('#status').textContent = 'Erro no núcleo GBA'; }; const rom = Uint8Array.from(payload.rom); const save = payload.save ? Uint8Array.from(payload.save) : null; worker.postMessage({ type: 'init', rom: rom.buffer, save: save?.buffer || null }, save ? [rom.buffer, save.buffer] : [rom.buffer]); setInterval(() => worker?.postMessage({ type: 'save' }), 5000); }
init().catch((error) => { console.error(error); document.querySelector('#status').textContent = 'Erro ao carregar ROM'; });
